#!/bin/bash
#$1: DATASET
#$2: TYPE
#$3: LA
#$4: LP
#$4: IP_ADDRESS
#$5: ASSIGNED_CORES
#$6: USERNAME

usage() { echo "Usage: $0 [-u user] [-i <string>] [-n <string>]" 1>&2; exit 1; }

while getopts ":n:i:" o; do
	
    case "${o}" in
    	u)
            USERNAME=${OPTARG}
            ;;

        n)
            SCREEN_NAME=${OPTARG}
            ;;
        i)
            ADDRESS=${OPTARG}
            ;;

        *)	
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${SCREEN_NAME}" ] || [ -z "${ADDRESS}" ]  ; then
    echo "Required field is missing."
    usage
fi


echo "----------------------------------------------------"
echo "     ATTACHING TO SCREEN:"${SCREEN_NAME}
echo "----------------------------------------------------"


ssh  -o "StrictHostKeyChecking no" -t -t ${USERNAME}@${ADDRESS} << EOF

screen -r ${SCREEN_NAME}
